name: Deploy to Dev

on:
  release:
    types: [ released ]
  
jobs:
  deploy-Lambda-function:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Setup AWS CLI v2
      uses: imehedi/actions-awscli-v2@latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "eu-east-1"
    - name: Create virtual environment
      run: |
        pip install virtualenv
        python3 -m virtualenv venv
    - name: Install requiremenents
      run: | 
        . venv/bin/activate
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install zappa
        deactivate
    - name: Deploy
      run: | 
        . venv/bin/activate
        zappa update dev
