name: Deploy to Dev

on:
  release:
    types: [ released ]
  
jobs:
  deploy-Lambda-function:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Setting up AWS Credentials
      run: |
        pip install awscli
        aws configure set region us-east-1
        aws configure set output json
        aws configure set aws_access_key_id ${{secrets.AWS_ACCESS_KEY_ID}}
        aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_ACCESS_KEY}}
    - name: Create virtual environment
      run: |
        pip install virtualenv
        python3 -m virtualenv venv
    - name: Install requiremenents
      run: | 
        . venv/bin/activate
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install zappa
        deactivate
    - name: Deploy
      run: | 
        . venv/bin/activate
        zappa update dev
